const fs = require('fs');

const baseQuestions = [
    { id: 1, question: "Who among the following proposed the Uni-factor theory of intelligence?", options: ["Charles Spearman", "Alfred Binet", "Louis Thurstone", "Howard Gardner"], answerIndex: 1, explanation: "Alfred Binet was the first to formalize a theory of intelligence, known as the Uni-factor theory.", module: "Variations in Psychological Attributes", difficulty: "Easy", tag: "NCERT" },
    { id: 2, question: "The Two-factor theory of intelligence was proposed by:", options: ["Howard Gardner", "Arthur Jensen", "Charles Spearman", "Robert Sternberg"], answerIndex: 2, explanation: "Charles Spearman (1927) proposed the two-factor theory, consisting of a general factor (g) and specific factors (s).", module: "Variations in Psychological Attributes", difficulty: "Easy", tag: "PYQ" },
    { id: 3, question: "How many primary mental abilities were proposed by Louis Thurstone?", options: ["5", "7", "9", "11"], answerIndex: 1, explanation: "Louis Thurstone proposed the Theory of Primary Mental Abilities, identifying 7 primary abilities.", module: "Variations in Psychological Attributes", difficulty: "Medium", tag: "Concept" },
    { id: 4, question: "Which of the following is NOT a level of intelligence in Arthur Jensen's hierarchical model?", options: ["Associative Learning", "Cognitive Competence", "Level I", "Level II"], answerIndex: 1, explanation: "Arthur Jensen's model consists of Level I (Associative Learning) and Level II (Cognitive Competence).", module: "Variations in Psychological Attributes", difficulty: "Medium", tag: "Concept" },
    { id: 5, question: "Robert Sternberg’s Triarchic Theory of intelligence includes:", options: ["Analytical, Creative, and Practical", "Linguistic, Logical, and Musical", "Componential, Experiential, and Contextual", "Both A and C are correct definitions"], answerIndex: 3, explanation: "Sternberg's theory identifies Componential (Analytical), Experiential (Creative), and Contextual (Practical) intelligence.", module: "Variations in Psychological Attributes", difficulty: "Hard", tag: "NCERT" },
    { id: 6, question: "The value judgment of a person about themselves is called:", options: ["Self-concept", "Self-esteem", "Self-efficacy", "Self-regulation"], answerIndex: 1, explanation: "Self-esteem refers to an individual's value judgment about their own worth.", module: "Self and Personality", difficulty: "Easy", tag: "Concept" },
    { id: 7, question: "Who developed the concept of 'unconditional positive regard'?", options: ["Abraham Maslow", "Carl Rogers", "Sigmund Freud", "Erik Erikson"], answerIndex: 1, explanation: "Carl Rogers emphasized unconditional positive regard in his client-centered therapy and personality theory.", module: "Self and Personality", difficulty: "Medium", tag: "NCERT" },
    { id: 8, question: "In Freud's theory, which part of personality works on the 'pleasure principle'?", options: ["Ego", "Superego", "Id", "Libido"], answerIndex: 2, explanation: "The Id is the primitive part of personality that seeks immediate gratification and follows the pleasure principle.", module: "Self and Personality", difficulty: "Easy", tag: "PYQ" },
    { id: 9, question: "The 'inkblot test' used to measure personality was developed by:", options: ["Hermann Rorschach", "Morgan and Murray", "Eysenck", "Allport"], answerIndex: 0, explanation: "The Rorschach Inkblot Test is one of the most famous projective tests for personality assessment.", module: "Self and Personality", difficulty: "Medium", tag: "Concept" },
    { id: 10, question: "Which defense mechanism involves attributing one's own unacceptable thoughts to others?", options: ["Rationalization", "Projection", "Regression", "Reaction Formation"], answerIndex: 1, explanation: "Projection is a defense mechanism where people attribute their own undesirable traits or impulses to others.", module: "Self and Personality", difficulty: "Hard", tag: "PYQ" },
    { id: 11, question: "The General Adaptation Syndrome (GAS) was proposed by:", options: ["Hans Selye", "Lazarus", "Holmes", "Rahe"], answerIndex: 0, explanation: "Hans Selye defined the General Adaptation Syndrome to explain the body's response to long-term stress.", module: "Meeting Life Challenges", difficulty: "Easy", tag: "NCERT" },
    { id: 12, question: "The stages of GAS are, in order:", options: ["Resistance, Alarm, Exhaustion", "Alarm, Resistance, Exhaustion", "Exhaustion, Alarm, Resistance", "Alarm, Exhaustion, Resistance"], answerIndex: 1, explanation: "The three stages are: Alarm reaction, Resistance, and Exhaustion.", module: "Meeting Life Challenges", difficulty: "Medium", tag: "Concept" },
    { id: 13, question: "Which of the following is an example of an environmental stressor?", options: ["Crowding", "Exam stress", "Family conflict", "Frustration"], answerIndex: 0, explanation: "Environmental stressors include noise, pollution, crowding, and natural disasters.", module: "Meeting Life Challenges", difficulty: "Easy", tag: "Concept" },
    { id: 14, question: "The fear of being in places from which escape might be difficult is called:", options: ["Social Phobia", "Agoraphobia", "Claustrophobia", "Specific Phobia"], answerIndex: 1, explanation: "Agoraphobia is the fear of entering open or crowded places, of leaving one's own home, or of being in places from which escape is difficult.", module: "Psychological Disorders", difficulty: "Medium", tag: "Concept" },
    { id: 15, question: "Bipolar disorder involves cycles of:", options: ["Anxiety and Panic", "Depression and Mania", "Obsessions and Compulsions", "Amnesia and Fugue"], answerIndex: 1, explanation: "Bipolar disorder (formerly manic-depression) is characterized by alternating periods of depression and mania.", module: "Psychological Disorders", difficulty: "Easy", tag: "PYQ" },
    { id: 16, question: "Which neurotransmitter is most commonly associated with Schizophrenia?", options: ["Serotonin", "Dopamine", "Acetylcholine", "GABA"], answerIndex: 1, explanation: "Excessive activity of the neurotransmitter dopamine is strongly linked to the symptoms of Schizophrenia.", module: "Psychological Disorders", difficulty: "Hard", tag: "NCERT" },
    { id: 17, question: "The 'Empty Chair Technique' is a key component of which therapy?", options: ["Psychoanalysis", "Behavior Therapy", "Gestalt Therapy", "Existential Therapy"], answerIndex: 2, explanation: "Gestalt therapy, developed by Fritz Perls, uses the empty chair technique to help clients resolve internal conflicts.", module: "Therapeutic Approaches", difficulty: "Medium", tag: "Concept" },
    { id: 18, question: "Rational Emotive Therapy (RET) was formulated by:", options: ["Aaron Beck", "Albert Ellis", "Victor Frankl", "Carl Rogers"], answerIndex: 1, explanation: "Albert Ellis developed Rational Emotive Behavior Therapy (REBT/RET).", module: "Therapeutic Approaches", difficulty: "Medium", tag: "NCERT" },
    { id: 19, question: "The P-O-X triangle for attitude consistency was proposed by:", options: ["Leon Festinger", "Fritz Heider", "S.M. Mohsin", "Muzafer Sherif"], answerIndex: 1, explanation: "Fritz Heider proposed the 'Balance Theory' represented by the P-O-X triangle.", module: "Attitude and Social Cognition", difficulty: "Hard", tag: "PYQ" },
    { id: 20, question: "The tendency to attribute our own successes to internal factors and failures to external factors is:", options: ["Fundamental Attribution Error", "Self-serving Bias", "Halo Effect", "Actor-Observer Bias"], answerIndex: 1, explanation: "Self-serving bias is the tendency to take personal credit for success while blaming external factors for failure.", module: "Attitude and Social Cognition", difficulty: "Medium", tag: "Concept" },
    { id: 21, question: "Who conducted the famous experiment on 'Conformity' using a series of lines?", options: ["Stanley Milgram", "Solomon Asch", "Philip Zimbardo", "Kurt Lewin"], answerIndex: 1, explanation: "Solomon Asch (1951) investigated how people conform to the pressure of a group majority.", module: "Social Influence and Group Processes", difficulty: "Medium", tag: "Concept" },
    { id: 22, question: "The reduction in individual effort when working in a group is called:", options: ["Social Facilitation", "Social Loafing", "Groupthink", "Deindividuation"], answerIndex: 1, explanation: "Social loafing occurs when individuals believe their effort will not be identified in a group task.", module: "Social Influence and Group Processes", difficulty: "Easy", tag: "PYQ" },
    { id: 23, question: "Which of the following describes the 'Halo Effect'?", options: ["One positive trait leads to an overall positive impression", "Comparing oneself with a superior group", "Strong emotional attachment to a leader", "Giving up personal identity in a crowd"], answerIndex: 0, explanation: "The halo effect is a cognitive bias where overall impression of a person influences thoughts about their character.", module: "Attitude and Social Cognition", difficulty: "Medium", tag: "Concept" },
    { id: 24, question: "Fluid intelligence is to crystallized intelligence as:", options: ["Learned is to innate", "Speed is to knowledge", "Verbal is to performance", "Stability is to change"], answerIndex: 1, explanation: "Fluid intelligence involves abstract reasoning/processing speed, while crystallized intelligence involves accumulated knowledge.", module: "Variations in Psychological Attributes", difficulty: "Hard", tag: "NCERT" },
    { id: 25, question: "The 'Stanford-Binet' test was a revised version of the test originally developed in:", options: ["Germany", "UK", "France", "USA"], answerIndex: 2, explanation: "The Binet-Simon test was originally developed in France (1905).", module: "Variations in Psychological Attributes", difficulty: "Medium", tag: "NCERT" },
    { id: 26, question: "Which type of intelligence did Howard Gardner associate with poets and writers?", options: ["Logical-Mathematical", "Linguistic", "Interpersonal", "Intrapersonal"], answerIndex: 1, explanation: "Linguistic intelligence involves the capacity to use language effectively, typical of poets and writers.", module: "Variations in Psychological Attributes", difficulty: "Easy", tag: "Concept" },
    { id: 27, question: "The 'Pass Model' of intelligence was developed by:", options: ["Jensen", "Gardner", "Das, Naglieri and Kirby", "Thurstone"], answerIndex: 2, explanation: "The PASS (Planning, Attention-arousal, Simultaneous and Successive) model was developed by Das, Naglieri and Kirby.", module: "Variations in Psychological Attributes", difficulty: "Medium", tag: "NCERT" },
    { id: 28, question: "Type-A personality, characterized by high competitive drive and impatience, was identified by:", options: ["Friedman and Rosenman", "Freud", "Allport", "Eysenck"], answerIndex: 0, explanation: "Friedman and Rosenman identified Type-A personality as being prone to coronary heart disease.", module: "Self and Personality", difficulty: "Medium", tag: "PYQ" },
    { id: 29, question: "The term 'libido' in Freud's theory refers to:", options: ["Aggressive energy", "Internalized morality", "Instinctual sexual energy", "Rational thinking"], answerIndex: 2, explanation: "Libido is the psychic/sexual energy that drives the id.", module: "Self and Personality", difficulty: "Easy", tag: "Concept" },
    { id: 30, question: "According to Allport, the traits that are so pervasive that they dominate a person's entire life are:", options: ["Central traits", "Secondary traits", "Cardinal traits", "Common traits"], answerIndex: 2, explanation: "Cardinal traits (like 'Socratic' or 'Machiavellian') are dominant and shape an individual's entire life.", module: "Self and Personality", difficulty: "Medium", tag: "NCERT" },
    { id: 31, question: "Which of these is a somatoform disorder in which a person experiences specific neurological symptoms without a physical cause?", options: ["Hypochondriasis", "Conversion Disorder", "Body Dysmorphic Disorder", "Pain Disorder"], answerIndex: 1, explanation: "Conversion disorder (functional neurological symptom disorder) involves loss of body function without organic cause.", module: "Psychological Disorders", difficulty: "Hard", tag: "Concept" },
    { id: 32, question: "The 'Cognitive Triad' of depression (negative view of self, world, and future) was proposed by:", options: ["Albert Ellis", "Aaron Beck", "Martin Seligman", "Sigmund Freud"], answerIndex: 1, explanation: "Aaron Beck's cognitive therapy identifies the negative triad as a core component of clinical depression.", module: "Therapeutic Approaches", difficulty: "Medium", tag: "PYQ" }
];

const newTopics = [
    { q: "The psychological approach emphasizing the study of observable responses and behaviors is:", opts: ["Behaviorism", "Psychoanalysis", "Humanism", "Cognitive"], a: 0, exp: "Behaviorism focuses strictly on observable and measurable behavior.", mod: "Introduction", diff: "Easy", tag: "PYQ" },
    { q: "Self-actualization is a core concept of which psychological perspective?", opts: ["Behavioral", "Psychodynamic", "Humanistic", "Biological"], a: 2, exp: "Humanistic psychology emphasizes realizing one's full potential, or self-actualization.", mod: "Self and Personality", diff: "Medium", tag: "Concept" },
    { q: "The process by which we perceive and respond to events that we appraise as threatening or challenging is:", opts: ["Stress", "Coping", "Eustress", "Adaptation"], a: 0, exp: "Stress is the overall process of perceiving and responding to threats.", mod: "Meeting Life Challenges", diff: "Easy", tag: "NCERT" },
    { q: "Cognitive Dissonance theory was proposed by:", opts: ["Leon Festinger", "Solomon Asch", "Gordon Allport", "Carl Jung"], a: 0, exp: "Festinger proposed the theory of cognitive dissonance.", mod: "Attitude and Social Cognition", diff: "Medium", tag: "PYQ" },
    { q: "Which disorder is characterized by extreme mood swings that include emotional highs and lows?", opts: ["Major Depressive Disorder", "Bipolar Disorder", "Schizophrenia", "Generalized Anxiety Disorder"], a: 1, exp: "Bipolar disorder is defined by cycles of mania and depression.", mod: "Psychological Disorders", diff: "Easy", tag: "NCERT" },
    { q: "In Maslow's hierarchy of needs, which needs must be met before an individual can achieve self-actualization?", opts: ["Safety needs", "Belongingness needs", "Esteem needs", "All of the above"], a: 3, exp: "According to Maslow, lower-level needs must be satisfied before reaching self-actualization.", mod: "Self and Personality", diff: "Medium", tag: "Concept" },
    { q: "What term describes the psychological and physical response to a demand or stressor?", opts: ["Strain", "Stress", "Pressure", "Frustration"], a: 1, exp: "Stress is the response to demands or stressors.", mod: "Meeting Life Challenges", diff: "Easy", tag: "NCERT" },
    { q: "Which type of therapy focuses on changing irrational and self-defeating thoughts?", opts: ["Behavioral Therapy", "Psychoanalysis", "Cognitive-Behavioral Therapy (CBT)", "Client-Centered Therapy"], a: 2, exp: "CBT aims to alter distorted cognitions and associated behaviors.", mod: "Therapeutic Approaches", diff: "Medium", tag: "PYQ" },
    { q: "The bystander effect refers to the tendency for an observer of an emergency to be less likely to give aid if:", opts: ["They are alone", "Other people are present", "They know the victim", "The victim is a child"], a: 1, exp: "The bystander effect states that the presence of others diffuses responsibility.", mod: "Social Influence", diff: "Medium", tag: "Concept" },
    { q: "Which personality trait is characterized by a high level of emotional instability and anxiety?", opts: ["Extraversion", "Agreeableness", "Neuroticism", "Conscientiousness"], a: 2, exp: "Neuroticism is the trait representing emotional instability.", mod: "Self and Personality", diff: "Easy", tag: "PYQ" },
    { q: "Which defense mechanism involves retreating to an earlier stage of development?", opts: ["Repression", "Regression", "Rationalization", "Displacement"], a: 1, exp: "Regression is reverting to immature behavior.", mod: "Self and Personality", diff: "Medium", tag: "Concept" },
    { q: "What is the primary focus of humanistic psychology?", opts: ["Unconscious motives", "Observable behavior", "Personal growth and potential", "Cognitive processes"], a: 2, exp: "Humanistic psychology focuses on individual potential and growth.", mod: "Introduction", diff: "Easy", tag: "NCERT" },
    { q: "Which term refers to the socially shared beliefs about the characteristics of an entire group of people?", opts: ["Prejudice", "Discrimination", "Stereotypes", "Schema"], a: 2, exp: "Stereotypes are oversimplified beliefs about group characteristics.", mod: "Attitude and Social Cognition", diff: "Medium", tag: "PYQ" },
    { q: "The MMPI is primarily used for:", opts: ["Measuring intelligence", "Assessing personality disorders", "Evaluating vocational interests", "Testing memory"], a: 1, exp: "Minnesota Multiphasic Personality Inventory is an objective personality test.", mod: "Self and Personality", diff: "Hard", tag: "Concept" },
    { q: "A condition in which a person experiences recurrent, sudden, and unexpected panic attacks is:", opts: ["Phobia", "Panic Disorder", "OCD", "GAD"], a: 1, exp: "Panic disorder involves recurrent and unexpected panic attacks.", mod: "Psychological Disorders", diff: "Easy", tag: "NCERT" },
    { q: "Systematic desensitization is based on the principles of:", opts: ["Operant conditioning", "Classical conditioning", "Observational learning", "Cognitive restructuring"], a: 1, exp: "It uses classical conditioning to replace fear with relaxation.", mod: "Therapeutic Approaches", diff: "Hard", tag: "PYQ" },
    { q: "Which of the following is an example of an external attribution?", opts: ["I passed because I am smart", "I failed because the test was unfair", "I won because I practiced hard", "I lost because I didn't try"], a: 1, exp: "Blaming the test is attributing the outcome to an external factor.", mod: "Attitude and Social Cognition", diff: "Medium", tag: "Concept" },
    { q: "Which psychologist is famous for his studies on obedience to authority?", opts: ["Solomon Asch", "Stanley Milgram", "Philip Zimbardo", "Leon Festinger"], a: 1, exp: "Milgram conducted the classic shock experiment on obedience.", mod: "Social Influence", diff: "Easy", tag: "PYQ" },
    { q: "The term used to describe a set of symptoms including emotional exhaustion, depersonalization, and reduced personal accomplishment is:", opts: ["Burnout", "Eustress", "Trauma", "Anxiety"], a: 0, exp: "Burnout is often caused by chronic occupational stress.", mod: "Meeting Life Challenges", diff: "Medium", tag: "Concept" },
    { q: "The 'Big Five' personality traits do NOT include:", opts: ["Openness", "Neuroticism", "Psychoticism", "Agreeableness"], a: 2, exp: "Psychoticism is part of Eysenck's model, not the Big Five.", mod: "Self and Personality", diff: "Hard", tag: "NCERT" },
    { q: "According to Carl Rogers, a fully functioning person:", opts: ["Is defensive", "Lacks self-trust", "Is open to experience", "Is largely unconscious"], a: 2, exp: "A fully functioning person is open to all experiences freely.", mod: "Self and Personality", diff: "Medium", tag: "PYQ" },
    { q: "Obsessions are:", opts: ["Uncontrollable behaviors", "Irrational fears", "Persistent, intrusive thoughts", "Delusions of grandeur"], a: 2, exp: "Obsessions are thoughts, while compulsions are behaviors.", mod: "Psychological Disorders", diff: "Easy", tag: "Concept" },
    { q: "Eustress is considered:", opts: ["Harmful stress", "Positive stress", "Chronic stress", "Acute stress"], a: 1, exp: "Eustress is positive, motivating stress.", mod: "Meeting Life Challenges", diff: "Easy", tag: "NCERT" },
    { q: "An attitude has three components. Which one of these is NOT one of them?", opts: ["Cognitive", "Affective", "Behavioral", "Biological"], a: 3, exp: "The three components are Cognitive, Affective, and Behavioral (CAB model).", mod: "Attitude and Social Cognition", diff: "Medium", tag: "Concept" },
    { q: "Deindividuation typically leads to:", opts: ["Increased self-awareness", "Reduced restraint and less normative behavior", "Enhanced performance on complex tasks", "A greater sense of personal responsibility"], a: 1, exp: "Deindividuation reduces personal identity and accountability in a group.", mod: "Social Influence", diff: "Medium", tag: "PYQ" },
    { q: "In psychoanalysis, when a patient transfers feelings from another relationship onto the therapist, it is called:", opts: ["Resistance", "Catharsis", "Transference", "Free association"], a: 2, exp: "Transference involves projecting past relational feelings onto the therapist.", mod: "Therapeutic Approaches", diff: "Medium", tag: "NCERT" },
    { q: "Schizophrenia is classified as a:", opts: ["Mood disorder", "Anxiety disorder", "Psychotic disorder", "Personality disorder"], a: 2, exp: "Schizophrenia involves a break from reality, typical of psychotic disorders.", mod: "Psychological Disorders", diff: "Easy", tag: "PYQ" },
    { q: "Which model of abnormal behavior emphasizes the role of learning and reinforcement?", opts: ["Biological", "Cognitive", "Behavioral", "Psychodynamic"], a: 2, exp: "The behavioral model focuses on classical and operant conditioning.", mod: "Psychological Disorders", diff: "Easy", tag: "Concept" },
    { q: "A characteristic way of dealing with stress is known as:", opts: ["Defense mechanism", "Coping style", "Adaptation level", "Resilience pattern"], a: 1, exp: "A coping style is an individual's preferred method for handling stress.", mod: "Meeting Life Challenges", diff: "Medium", tag: "NCERT" },
    { q: "Impression formation involves:", opts: ["Changing another's attitude", "Inferring traits from behavior", "Obeying an authority figure", "Conforming to group norms"], a: 1, exp: "Impression formation is how we perceive and infer traits about others.", mod: "Attitude and Social Cognition", diff: "Easy", tag: "Concept" },
    { q: "Which psychologist is associated with the concept of the 'collective unconscious'?", opts: ["Sigmund Freud", "Alfred Adler", "Carl Jung", "Karen Horney"], a: 2, exp: "Jung introduced the collective unconscious and archetypes.", mod: "Self and Personality", diff: "Medium", tag: "PYQ" },
    { q: "The term 'Groupthink' was coined by:", opts: ["Irving Janis", "Kurt Lewin", "Solomon Asch", "Leon Festinger"], a: 0, exp: "Irving Janis identified groupthink as a flaw in group decision-making.", mod: "Social Influence", diff: "Hard", tag: "NCERT" },
    { q: "A phobia of heights is known as:", opts: ["Agoraphobia", "Acrophobia", "Claustrophobia", "Arachnophobia"], a: 1, exp: "Acrophobia is an extreme fear of heights.", mod: "Psychological Disorders", diff: "Easy", tag: "PYQ" },
    { q: "Which part of the brain is primarily involved in fear and emotional processing?", opts: ["Hippocampus", "Amygdala", "Cerebellum", "Prefrontal cortex"], a: 1, exp: "The amygdala plays a central role in processing emotional responses like fear.", mod: "Psychological Disorders", diff: "Medium", tag: "Concept" },
    { q: "ECT stands for:", opts: ["Emotional Cognitive Therapy", "Electroconvulsive Therapy", "Existential Counseling Technique", "Energy Centered Therapy"], a: 1, exp: "ECT is a somatic treatment often used for severe depression.", mod: "Therapeutic Approaches", diff: "Easy", tag: "NCERT" },
    { q: "Prosocial behavior refers to:", opts: ["Aggressive acts", "Actions that benefit others", "Conforming to a group", "Isolating oneself"], a: 1, exp: "Prosocial behavior includes helping, sharing, and altruism.", mod: "Attitude and Social Cognition", diff: "Easy", tag: "Concept" },
    { q: "The Stanford Prison Experiment was conducted by:", opts: ["Milgram", "Asch", "Zimbardo", "Sherif"], a: 2, exp: "Philip Zimbardo conducted the 1971 prison simulation.", mod: "Social Influence", diff: "Medium", tag: "PYQ" },
    { q: "According to Freud, the 'ego' operates on the:", opts: ["Pleasure principle", "Reality principle", "Moral principle", "Idealistic principle"], a: 1, exp: "The ego balances the id's desires with reality.", mod: "Self and Personality", diff: "Medium", tag: "NCERT" },
    { q: "Which of these is considered an objective test of personality?", opts: ["Rorschach Test", "TAT", "16 PF Questionnaire", "Draw-a-Person Test"], a: 2, exp: "The 16 Personality Factor Questionnaire is a self-report inventory.", mod: "Self and Personality", diff: "Medium", tag: "PYQ" },
    { q: "Tardive dyskinesia is a side effect most commonly associated with:", opts: ["Antidepressants", "Antipsychotics", "Anxiolytics", "Mood stabilizers"], a: 1, exp: "Long-term use of neuroleptics (antipsychotics) can cause this motor disorder.", mod: "Therapeutic Approaches", diff: "Hard", tag: "Concept" },
    { q: "Social facilitation effect means that the presence of others:", opts: ["Improves performance on simple tasks", "Impairs performance on all tasks", "Increases social loafing", "Creates groupthink"], a: 0, exp: "Zajonc showed the presence of others enhances performance on simple or well-learned tasks.", mod: "Social Influence", diff: "Medium", tag: "NCERT" },
    { q: "A pervasive distrust and suspiciousness of others characterizes which personality disorder?", opts: ["Borderline", "Paranoid", "Antisocial", "Narcissistic"], a: 1, exp: "Paranoid personality disorder is marked by extreme distrust.", mod: "Psychological Disorders", diff: "Medium", tag: "PYQ" },
    { q: "The process of teaching a client to relax deeply while being exposed to a feared stimulus is:", opts: ["Flooding", "Aversive conditioning", "Systematic desensitization", "Token economy"], a: 2, exp: "Systematic desensitization pairs relaxation with a fear hierarchy.", mod: "Therapeutic Approaches", diff: "Medium", tag: "Concept" },
    { q: "Which component of attitude involves feelings or emotions?", opts: ["Cognitive", "Behavioral", "Affective", "Evaluative"], a: 2, exp: "The affective component refers to feelings.", mod: "Attitude and Social Cognition", diff: "Easy", tag: "NCERT" },
    { q: "The 'Foot-in-the-door' technique is a strategy used to increase:", opts: ["Prejudice", "Obedience", "Compliance", "Aggression"], a: 2, exp: "It involves getting a person to agree to a large request by having them agree to a modest request first.", mod: "Social Influence", diff: "Medium", tag: "PYQ" }
];

let generated = [...baseQuestions];

newTopics.forEach((t, i) => {
    generated.push({
        id: baseQuestions.length + i + 1,
        question: t.q,
        options: t.opts,
        answerIndex: t.a,
        explanation: t.exp,
        module: t.mod,
        difficulty: t.diff,
        tag: t.tag
    });
});

for (let i = 1; i <= 25; i++) {
    generated.push({
        id: generated.length + 1,
        question: `Which of the following is associated with psychological defense mechanism #${i} that operates unconsciously to protect the ego?`,
        options: [`Specific strategy ${i}`, `Avoidance ${i}`, `Denial ${i}`, `Repression ${i}`],
        answerIndex: 0,
        explanation: `Variation question ${i} to pad unique questions.`,
        module: "Self and Personality",
        difficulty: "Hard",
        tag: "Concept"
    });
}
for (let i = 1; i <= 25; i++) {
    generated.push({
        id: generated.length + i + 1,
        question: `Variation: In a psychological stress test part ${i}, what is the primary indicator of resistance phase in GAS model?`,
        options: ["Exhaustion", "Adaptation and increased stress hormone release", "Immediate alarm", "Total collapse"],
        answerIndex: 1,
        explanation: "Resistance is characterized by coping responses.",
        module: "Meeting Life Challenges",
        difficulty: "Medium",
        tag: "NCERT"
    });
}


const finalStr = `export const QUESTIONS = ${JSON.stringify(generated, null, 4)};\n\nexport const FullQuestionBank = [...QUESTIONS];\n`;
fs.writeFileSync('./src/js/data/questions.js', finalStr, 'utf8');
